//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:38:20 PM CST 
//


package com.javameta.model.fieldpool;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javameta.model.fieldpool package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {
	private static final long serialVersionUID = 1L;


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javameta.model.fieldpool
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Field.RelationDS.RelationItem.RelationExpr }
     * 
     */
    public Field.RelationDS.RelationItem.RelationExpr createFieldRelationDSRelationItemRelationExpr() {
        return new Field.RelationDS.RelationItem.RelationExpr();
    }

    /**
     * Create an instance of {@link Field.CalcValueExpr }
     * 
     */
    public Field.CalcValueExpr createFieldCalcValueExpr() {
        return new Field.CalcValueExpr();
    }

    /**
     * Create an instance of {@link Field.RelationDS }
     * 
     */
    public Field.RelationDS createFieldRelationDS() {
        return new Field.RelationDS();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Field.RelationDS.RelationItem }
     * 
     */
    public Field.RelationDS.RelationItem createFieldRelationDSRelationItem() {
        return new Field.RelationDS.RelationItem();
    }

    /**
     * Create an instance of {@link Fields }
     * 
     */
    public Fields createFields() {
        return new Fields();
    }

    /**
     * Create an instance of {@link Field.FormatExpr }
     * 
     */
    public Field.FormatExpr createFieldFormatExpr() {
        return new Field.FormatExpr();
    }

    /**
     * Create an instance of {@link Field.DefaultValueExpr }
     * 
     */
    public Field.DefaultValueExpr createFieldDefaultValueExpr() {
        return new Field.DefaultValueExpr();
    }

    /**
     * Create an instance of {@link Field.ValidateExpr }
     * 
     */
    public Field.ValidateExpr createFieldValidateExpr() {
        return new Field.ValidateExpr();
    }

}
