//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 11:22:50 AM CST 
//

package com.javameta.model.datasource;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="primaryKey">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="id" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="PRIMARY_KEY" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="createBy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="createBy" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="CREATE_BY" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="createTime">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="createTime" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="CREATE_TIME" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="createUnit">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="createUnit" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="CREATE_UNIT" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="modifyBy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="modifyBy" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="MODIFY_BY" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="modifyUnit">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="modifyUnit" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="MODIFY_UNIT" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="modifyTime">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="modifyTime" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="MODIFY_TIME" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="remark" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{https://github.com/hongjinqiu/javameta/datasource}field-group"/>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="remark" />
 *                 &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="REMARK" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "primaryKey", "createBy", "createTime", "createUnit", "modifyBy", "modifyUnit", "modifyTime", "remark" })
@XmlRootElement(name = "fixField")
public class FixField implements Serializable {
	private static final long serialVersionUID = 1L;

	@XmlElement(required = true)
	protected Field primaryKey;
	@XmlElement(required = true)
	protected Field createBy;
	@XmlElement(required = true)
	protected Field createTime;
	@XmlElement(required = true)
	protected Field createUnit;
	@XmlElement(required = true)
	protected Field modifyBy;
	@XmlElement(required = true)
	protected Field modifyUnit;
	@XmlElement(required = true)
	protected Field modifyTime;
	protected Field remark;

	public Field getPrimaryKey() {
		return primaryKey;
	}

	public void setPrimaryKey(Field primaryKey) {
		this.primaryKey = primaryKey;
	}

	public Field getCreateBy() {
		return createBy;
	}

	public void setCreateBy(Field createBy) {
		this.createBy = createBy;
	}

	public Field getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Field createTime) {
		this.createTime = createTime;
	}

	public Field getCreateUnit() {
		return createUnit;
	}

	public void setCreateUnit(Field createUnit) {
		this.createUnit = createUnit;
	}

	public Field getModifyBy() {
		return modifyBy;
	}

	public void setModifyBy(Field modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Field getModifyUnit() {
		return modifyUnit;
	}

	public void setModifyUnit(Field modifyUnit) {
		this.modifyUnit = modifyUnit;
	}

	public Field getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Field modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Field getRemark() {
		return remark;
	}

	public void setRemark(Field remark) {
		this.remark = remark;
	}

}
