//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:38:20 PM CST 
//


package com.javameta.model.fieldpool;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{https://github.com/hongjinqiu/javameta/fieldpool}field-group"/>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldName",
    "displayName",
    "fieldType",
    "fieldLength",
    "decimalPointLength",
    "defaultValueExpr",
    "checkInUsed",
    "fixHide",
    "fixReadOnly",
    "allowCopy",
    "allowDuplicate",
    "denyEditInUsed",
    "allowEmpty",
    "limitOption",
    "limitMax",
    "limitMin",
    "validateExpr",
    "validateMessage",
    "dictionary",
    "dictionaryWhere",
    "calcValueExpr",
    "zeroShowEmpty",
    "formatExpr",
    "relationDS"
})
@XmlRootElement(name = "field")
public class Field implements Serializable {
	private static final long serialVersionUID = 1L;

    protected String fieldName;
    protected String displayName;
    protected String fieldType;
    @XmlElement(defaultValue = "20")
    protected Integer fieldLength;
    @XmlElement(defaultValue = "4")
    protected Integer decimalPointLength;
    protected Field.DefaultValueExpr defaultValueExpr;
    @XmlElement(defaultValue = "true")
    protected Boolean checkInUsed;
    @XmlElement(defaultValue = "false")
    protected Boolean fixHide;
    @XmlElement(defaultValue = "false")
    protected Boolean fixReadOnly;
    @XmlElement(defaultValue = "true")
    protected Boolean allowCopy;
    @XmlElement(defaultValue = "true")
    protected Boolean allowDuplicate;
    @XmlElement(defaultValue = "false")
    protected Boolean denyEditInUsed;
    @XmlElement(defaultValue = "true")
    protected Boolean allowEmpty;
    protected String limitOption;
    @XmlElement(defaultValue = "")
    protected String limitMax;
    @XmlElement(defaultValue = "")
    protected String limitMin;
    protected Field.ValidateExpr validateExpr;
    @XmlElement(defaultValue = "")
    protected String validateMessage;
    @XmlElement(defaultValue = "")
    protected String dictionary;
    @XmlElement(defaultValue = "")
    protected String dictionaryWhere;
    protected Field.CalcValueExpr calcValueExpr;
    @XmlElement(defaultValue = "false")
    protected Boolean zeroShowEmpty;
    protected Field.FormatExpr formatExpr;
    protected Field.RelationDS relationDS;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "extends")
    @XmlSchemaType(name = "anySimpleType")
    protected String _extends;

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldName(String value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the fieldType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * Sets the value of the fieldType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldType(String value) {
        this.fieldType = value;
    }

    /**
     * Gets the value of the fieldLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFieldLength() {
        return fieldLength;
    }

    /**
     * Sets the value of the fieldLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFieldLength(Integer value) {
        this.fieldLength = value;
    }

    /**
     * Gets the value of the decimalPointLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDecimalPointLength() {
        return decimalPointLength;
    }

    /**
     * Sets the value of the decimalPointLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDecimalPointLength(Integer value) {
        this.decimalPointLength = value;
    }

    /**
     * Gets the value of the defaultValueExpr property.
     * 
     * @return
     *     possible object is
     *     {@link Field.DefaultValueExpr }
     *     
     */
    public Field.DefaultValueExpr getDefaultValueExpr() {
        return defaultValueExpr;
    }

    /**
     * Sets the value of the defaultValueExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.DefaultValueExpr }
     *     
     */
    public void setDefaultValueExpr(Field.DefaultValueExpr value) {
        this.defaultValueExpr = value;
    }

    /**
     * Gets the value of the checkInUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckInUsed() {
        return checkInUsed;
    }

	public Boolean getCheckInUsed() {
        return checkInUsed;
    }

    /**
     * Sets the value of the checkInUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckInUsed(Boolean value) {
        this.checkInUsed = value;
    }

    /**
     * Gets the value of the fixHide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFixHide() {
        return fixHide;
    }

	public Boolean getFixHide() {
        return fixHide;
    }

    /**
     * Sets the value of the fixHide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixHide(Boolean value) {
        this.fixHide = value;
    }

    /**
     * Gets the value of the fixReadOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFixReadOnly() {
        return fixReadOnly;
    }

	public Boolean getFixReadOnly() {
        return fixReadOnly;
    }

    /**
     * Sets the value of the fixReadOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixReadOnly(Boolean value) {
        this.fixReadOnly = value;
    }

    /**
     * Gets the value of the allowCopy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowCopy() {
        return allowCopy;
    }

	public Boolean getAllowCopy() {
        return allowCopy;
    }

    /**
     * Sets the value of the allowCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowCopy(Boolean value) {
        this.allowCopy = value;
    }

    /**
     * Gets the value of the allowDuplicate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowDuplicate() {
        return allowDuplicate;
    }

	public Boolean getAllowDuplicate() {
        return allowDuplicate;
    }

    /**
     * Sets the value of the allowDuplicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowDuplicate(Boolean value) {
        this.allowDuplicate = value;
    }

    /**
     * Gets the value of the denyEditInUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDenyEditInUsed() {
        return denyEditInUsed;
    }

	public Boolean getDenyEditInUsed() {
        return denyEditInUsed;
    }

    /**
     * Sets the value of the denyEditInUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDenyEditInUsed(Boolean value) {
        this.denyEditInUsed = value;
    }

    /**
     * Gets the value of the allowEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowEmpty() {
        return allowEmpty;
    }

	public Boolean getAllowEmpty() {
        return allowEmpty;
    }

    /**
     * Sets the value of the allowEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowEmpty(Boolean value) {
        this.allowEmpty = value;
    }

    /**
     * Gets the value of the limitOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitOption() {
        return limitOption;
    }

    /**
     * Sets the value of the limitOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitOption(String value) {
        this.limitOption = value;
    }

    /**
     * Gets the value of the limitMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitMax() {
        return limitMax;
    }

    /**
     * Sets the value of the limitMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitMax(String value) {
        this.limitMax = value;
    }

    /**
     * Gets the value of the limitMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitMin() {
        return limitMin;
    }

    /**
     * Sets the value of the limitMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitMin(String value) {
        this.limitMin = value;
    }

    /**
     * Gets the value of the validateExpr property.
     * 
     * @return
     *     possible object is
     *     {@link Field.ValidateExpr }
     *     
     */
    public Field.ValidateExpr getValidateExpr() {
        return validateExpr;
    }

    /**
     * Sets the value of the validateExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.ValidateExpr }
     *     
     */
    public void setValidateExpr(Field.ValidateExpr value) {
        this.validateExpr = value;
    }

    /**
     * Gets the value of the validateMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidateMessage() {
        return validateMessage;
    }

    /**
     * Sets the value of the validateMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidateMessage(String value) {
        this.validateMessage = value;
    }

    /**
     * Gets the value of the dictionary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDictionary() {
        return dictionary;
    }

    /**
     * Sets the value of the dictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDictionary(String value) {
        this.dictionary = value;
    }

    /**
     * Gets the value of the dictionaryWhere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDictionaryWhere() {
        return dictionaryWhere;
    }

    /**
     * Sets the value of the dictionaryWhere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDictionaryWhere(String value) {
        this.dictionaryWhere = value;
    }

    /**
     * Gets the value of the calcValueExpr property.
     * 
     * @return
     *     possible object is
     *     {@link Field.CalcValueExpr }
     *     
     */
    public Field.CalcValueExpr getCalcValueExpr() {
        return calcValueExpr;
    }

    /**
     * Sets the value of the calcValueExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.CalcValueExpr }
     *     
     */
    public void setCalcValueExpr(Field.CalcValueExpr value) {
        this.calcValueExpr = value;
    }

    /**
     * Gets the value of the zeroShowEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZeroShowEmpty() {
        return zeroShowEmpty;
    }

	public Boolean getZeroShowEmpty() {
        return zeroShowEmpty;
    }

    /**
     * Sets the value of the zeroShowEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZeroShowEmpty(Boolean value) {
        this.zeroShowEmpty = value;
    }

    /**
     * Gets the value of the formatExpr property.
     * 
     * @return
     *     possible object is
     *     {@link Field.FormatExpr }
     *     
     */
    public Field.FormatExpr getFormatExpr() {
        return formatExpr;
    }

    /**
     * Sets the value of the formatExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.FormatExpr }
     *     
     */
    public void setFormatExpr(Field.FormatExpr value) {
        this.formatExpr = value;
    }

    /**
     * Gets the value of the relationDS property.
     * 
     * @return
     *     possible object is
     *     {@link Field.RelationDS }
     *     
     */
    public Field.RelationDS getRelationDS() {
        return relationDS;
    }

    /**
     * Sets the value of the relationDS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.RelationDS }
     *     
     */
    public void setRelationDS(Field.RelationDS value) {
        this.relationDS = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtends(String value) {
        this._extends = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="mode" default="text">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="text"/>
     *             &lt;enumeration value="js"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CalcValueExpr implements Serializable {
		private static final long serialVersionUID = 1L;

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String mode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="mode" default="text">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="text"/>
     *             &lt;enumeration value="js"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DefaultValueExpr implements Serializable {
		private static final long serialVersionUID = 1L;

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String mode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="mode" default="text">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="text"/>
     *             &lt;enumeration value="js"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FormatExpr implements Serializable {
		private static final long serialVersionUID = 1L;

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String mode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="relationItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="relationExpr">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="mode" default="text">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="text"/>
     *                                 &lt;enumeration value="js"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="relationModelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="relationDataSetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="displayField" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="valueField" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relationItem"
    })
    public static class RelationDS implements Serializable {
		private static final long serialVersionUID = 1L;

        protected List<Field.RelationDS.RelationItem> relationItem;

        /**
         * Gets the value of the relationItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relationItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelationItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Field.RelationDS.RelationItem }
         * 
         * 
         */
        public List<Field.RelationDS.RelationItem> getRelationItem() {
            if (relationItem == null) {
                relationItem = new ArrayList<Field.RelationDS.RelationItem>();
            }
            return this.relationItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="relationExpr">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="mode" default="text">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="text"/>
         *                       &lt;enumeration value="js"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="relationModelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="relationDataSetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="displayField" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="valueField" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "relationExpr",
            "relationModelId",
            "relationDataSetId",
            "displayField",
            "valueField"
        })
        public static class RelationItem implements Serializable {
		private static final long serialVersionUID = 1L;

            @XmlElement(required = true, defaultValue = "R")
            protected String id;
            @XmlElement(required = true, defaultValue = "1")
            protected Field.RelationDS.RelationItem.RelationExpr relationExpr;
            @XmlElement(required = true, defaultValue = "")
            protected String relationModelId;
            @XmlElement(required = true, defaultValue = "")
            protected String relationDataSetId;
            @XmlElement(required = true, defaultValue = "")
            protected String displayField;
            @XmlElement(required = true, defaultValue = "")
            protected String valueField;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String name;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the relationExpr property.
             * 
             * @return
             *     possible object is
             *     {@link Field.RelationDS.RelationItem.RelationExpr }
             *     
             */
            public Field.RelationDS.RelationItem.RelationExpr getRelationExpr() {
                return relationExpr;
            }

            /**
             * Sets the value of the relationExpr property.
             * 
             * @param value
             *     allowed object is
             *     {@link Field.RelationDS.RelationItem.RelationExpr }
             *     
             */
            public void setRelationExpr(Field.RelationDS.RelationItem.RelationExpr value) {
                this.relationExpr = value;
            }

            /**
             * Gets the value of the relationModelId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelationModelId() {
                return relationModelId;
            }

            /**
             * Sets the value of the relationModelId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelationModelId(String value) {
                this.relationModelId = value;
            }

            /**
             * Gets the value of the relationDataSetId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelationDataSetId() {
                return relationDataSetId;
            }

            /**
             * Sets the value of the relationDataSetId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelationDataSetId(String value) {
                this.relationDataSetId = value;
            }

            /**
             * Gets the value of the displayField property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayField() {
                return displayField;
            }

            /**
             * Sets the value of the displayField property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayField(String value) {
                this.displayField = value;
            }

            /**
             * Gets the value of the valueField property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueField() {
                return valueField;
            }

            /**
             * Sets the value of the valueField property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueField(String value) {
                this.valueField = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="mode" default="text">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="text"/>
             *             &lt;enumeration value="js"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class RelationExpr implements Serializable {
            	private static final long serialVersionUID = 1L;

                @XmlValue
                protected String value;
                @XmlAttribute
                protected String mode;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the mode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMode() {
                    return mode;
                }

                /**
                 * Sets the value of the mode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMode(String value) {
                    this.mode = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="mode" default="text">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="text"/>
     *             &lt;enumeration value="js"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ValidateExpr implements Serializable {
		private static final long serialVersionUID = 1L;

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String mode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }

}
