//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 04:39:16 PM CST 
//


package com.javameta.model.template;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{https://github.com/hongjinqiu/javameta/template}button"/>
 *         &lt;element ref="{https://github.com/hongjinqiu/javameta/template}split-button"/>
 *       &lt;/choice>
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="columns" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="iconAlign" default="left">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="top"/>
 *             &lt;enumeration value="right"/>
 *             &lt;enumeration value="bottom"/>
 *             &lt;enumeration value="left"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="scale" default="small">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="small"/>
 *             &lt;enumeration value="medium"/>
 *             &lt;enumeration value="large"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "buttonOrSplitButton"
})
@XmlRootElement(name = "button-group")
public class ButtonGroup implements Serializable {
	private static final long serialVersionUID = 1L;

    @XmlElements({
        @XmlElement(name = "button", type = Button.class),
        @XmlElement(name = "split-button", type = SplitButton.class)
    })
    protected List<Object> buttonOrSplitButton;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String title;
    @XmlAttribute(required = true)
    protected int columns;
    @XmlAttribute
    protected String iconAlign;
    @XmlAttribute
    protected String scale;

    /**
     * Gets the value of the buttonOrSplitButton property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buttonOrSplitButton property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getButtonOrSplitButton().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Button }
     * {@link SplitButton }
     * 
     * 
     */
    public List<Object> getButtonOrSplitButton() {
        if (buttonOrSplitButton == null) {
            buttonOrSplitButton = new ArrayList<Object>();
        }
        return this.buttonOrSplitButton;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     */
    public Integer getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     */
    public void setColumns(int value) {
        this.columns = value;
    }

    /**
     * Gets the value of the iconAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconAlign() {
        return iconAlign;
    }

    /**
     * Sets the value of the iconAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconAlign(String value) {
        this.iconAlign = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScale(String value) {
        this.scale = value;
    }

	@XmlTransient
    private String xmlName = "button-group";

    public String getXmlName() {
		return xmlName;
	}

	public void setXmlName(String xmlName) {
		this.xmlName = xmlName;
	}
}
