//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 04:39:16 PM CST 
//


package com.javameta.model.template;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javameta.model.template package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {
	private static final long serialVersionUID = 1L;

    private final static QName _DatasourceModelId_QNAME = new QName("https://github.com/hongjinqiu/javameta/template", "data-source-model-id");
    private final static QName _AfterQueryData_QNAME = new QName("https://github.com/hongjinqiu/javameta/template", "after-query-data");
    private final static QName _Id_QNAME = new QName("https://github.com/hongjinqiu/javameta/template", "id");
    private final static QName _Scripts_QNAME = new QName("https://github.com/hongjinqiu/javameta/template", "scripts");
    private final static QName _Description_QNAME = new QName("https://github.com/hongjinqiu/javameta/template", "description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javameta.model.template
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryParameters.QueryParameter.ParameterAttribute }
     * 
     */
    public QueryParameters.QueryParameter.ParameterAttribute createQueryParametersQueryParameterParameterAttribute() {
        return new QueryParameters.QueryParameter.ParameterAttribute();
    }

    /**
     * Create an instance of {@link VirtualColumn }
     * 
     */
    public VirtualColumn createVirtualColumn() {
        return new VirtualColumn();
    }

    /**
     * Create an instance of {@link DictionaryColumn }
     * 
     */
    public DictionaryColumn createDictionaryColumn() {
        return new DictionaryColumn();
    }

    /**
     * Create an instance of {@link VirtualColumn.Buttons }
     * 
     */
    public VirtualColumn.Buttons createVirtualColumnButtons() {
        return new VirtualColumn.Buttons();
    }

    /**
     * Create an instance of {@link EditorToolbar }
     * 
     */
    public EditorToolbar createEditorToolbar() {
        return new EditorToolbar();
    }

    /**
     * Create an instance of {@link Button }
     * 
     */
    public Button createButton() {
        return new Button();
    }

    /**
     * Create an instance of {@link CheckboxColumn }
     * 
     */
    public CheckboxColumn createCheckboxColumn() {
        return new CheckboxColumn();
    }

    /**
     * Create an instance of {@link RelationDS.RelationItem.RelationExpr }
     * 
     */
    public RelationDS.RelationItem.RelationExpr createRelationDSRelationItemRelationExpr() {
        return new RelationDS.RelationItem.RelationExpr();
    }

    /**
     * Create an instance of {@link Editor }
     * 
     */
    public Editor createEditor() {
        return new Editor();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link StringColumn }
     * 
     */
    public StringColumn createStringColumn() {
        return new StringColumn();
    }

    /**
     * Create an instance of {@link BooleanColumn }
     * 
     */
    public BooleanColumn createBooleanColumn() {
        return new BooleanColumn();
    }

    /**
     * Create an instance of {@link Toolbar }
     * 
     */
    public Toolbar createToolbar() {
        return new Toolbar();
    }

    /**
     * Create an instance of {@link ViewTemplate }
     * 
     */
    public ViewTemplate createViewTemplate() {
        return new ViewTemplate();
    }

    /**
     * Create an instance of {@link Listeners }
     * 
     */
    public Listeners createListeners() {
        return new Listeners();
    }

    /**
     * Create an instance of {@link ButtonGroup }
     * 
     */
    public ButtonGroup createButtonGroup() {
        return new ButtonGroup();
    }

    /**
     * Create an instance of {@link FormTemplate }
     * 
     */
    public FormTemplate createFormTemplate() {
        return new FormTemplate();
    }

    /**
     * Create an instance of {@link DataProvider.SummarySql }
     * 
     */
    public DataProvider.SummarySql createDataProviderSummarySql() {
        return new DataProvider.SummarySql();
    }

    /**
     * Create an instance of {@link ColumnModel }
     * 
     */
    public ColumnModel createColumnModel() {
        return new ColumnModel();
    }

    /**
     * Create an instance of {@link QueryParameters.QueryParameter }
     * 
     */
    public QueryParameters.QueryParameter createQueryParametersQueryParameter() {
        return new QueryParameters.QueryParameter();
    }

    /**
     * Create an instance of {@link AutoColumn }
     * 
     */
    public AutoColumn createAutoColumn() {
        return new AutoColumn();
    }

    /**
     * Create an instance of {@link RelationDS.RelationItem.CopyConfig }
     * 
     */
    public RelationDS.RelationItem.CopyConfig createRelationDSRelationItemCopyConfig() {
        return new RelationDS.RelationItem.CopyConfig();
    }

    /**
     * Create an instance of {@link Adapter }
     * 
     */
    public Adapter createAdapter() {
        return new Adapter();
    }

    /**
     * Create an instance of {@link QueryParameters }
     * 
     */
    public QueryParameters createQueryParameters() {
        return new QueryParameters();
    }

    /**
     * Create an instance of {@link DataProvider.TemplateSql }
     * 
     */
    public DataProvider.TemplateSql createDataProviderTemplateSql() {
        return new DataProvider.TemplateSql();
    }

    /**
     * Create an instance of {@link Cookie }
     * 
     */
    public Cookie createCookie() {
        return new Cookie();
    }
    
    /**
     * Create an instance of {@link HtmlFragment }
     * 
     */
    public HtmlFragment createHtmlFragment() {
        return new HtmlFragment();
    }

    /**
     * Create an instance of {@link Button.ButtonAttribute }
     * 
     */
    public Button.ButtonAttribute createButtonButtonAttribute() {
        return new Button.ButtonAttribute();
    }

    /**
     * Create an instance of {@link DateColumn }
     * 
     */
    public DateColumn createDateColumn() {
        return new DateColumn();
    }

    /**
     * Create an instance of {@link IdColumn }
     * 
     */
    public IdColumn createIdColumn() {
        return new IdColumn();
    }

    /**
     * Create an instance of {@link Expression }
     * 
     */
    public Expression createExpression() {
        return new Expression();
    }

    /**
     * Create an instance of {@link DataProvider }
     * 
     */
    public DataProvider createDataProvider() {
        return new DataProvider();
    }

    /**
     * Create an instance of {@link Editor.EditorAttribute }
     * 
     */
    public Editor.EditorAttribute createEditorEditorAttribute() {
        return new Editor.EditorAttribute();
    }

    /**
     * Create an instance of {@link RelationDS }
     * 
     */
    public RelationDS createRelationDS() {
        return new RelationDS();
    }

    /**
     * Create an instance of {@link RelationDS.RelationItem.RelationConfig }
     * 
     */
    public RelationDS.RelationItem.RelationConfig createRelationDSRelationItemRelationConfig() {
        return new RelationDS.RelationItem.RelationConfig();
    }

    /**
     * Create an instance of {@link TriggerColumn }
     * 
     */
    public TriggerColumn createTriggerColumn() {
        return new TriggerColumn();
    }

    /**
     * Create an instance of {@link QueryParameters.FixedParameter }
     * 
     */
    public QueryParameters.FixedParameter createQueryParametersFixedParameter() {
        return new QueryParameters.FixedParameter();
    }

    /**
     * Create an instance of {@link NumberColumn }
     * 
     */
    public NumberColumn createNumberColumn() {
        return new NumberColumn();
    }

    /**
     * Create an instance of {@link SplitButton }
     * 
     */
    public SplitButton createSplitButton() {
        return new SplitButton();
    }

    /**
     * Create an instance of {@link RelationDS.RelationItem }
     * 
     */
    public RelationDS.RelationItem createRelationDSRelationItem() {
        return new RelationDS.RelationItem();
    }

    /**
     * Create an instance of {@link QueryParameters.QueryParameter.DefaultValueExpr }
     * 
     */
    public QueryParameters.QueryParameter.DefaultValueExpr createQueryParametersQueryParameterDefaultValueExpr() {
        return new QueryParameters.QueryParameter.DefaultValueExpr();
    }

    /**
     * Create an instance of {@link ColumnAttribute }
     * 
     */
    public ColumnAttribute createColumnAttribute() {
        return new ColumnAttribute();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/hongjinqiu/javameta/template", name = "data-source-model-id")
    public JAXBElement<String> createDatasourceModelId(String value) {
        return new JAXBElement<String>(_DatasourceModelId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/hongjinqiu/javameta/template", name = "after-query-data")
    public JAXBElement<String> createAfterQueryData(String value) {
        return new JAXBElement<String>(_AfterQueryData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/hongjinqiu/javameta/template", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/hongjinqiu/javameta/template", name = "scripts")
    public JAXBElement<String> createScripts(String value) {
        return new JAXBElement<String>(_Scripts_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/hongjinqiu/javameta/template", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

}
