//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 04:39:16 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/hongjinqiu/javameta/template", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.javameta.model.template;
