//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 04:39:16 PM CST 
//


package com.javameta.model.template;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.apache.commons.lang3.StringUtils;

import com.javameta.util.New;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="fixed-parameter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{https://github.com/hongjinqiu/javameta/template}query-param-attributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="query-parameter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parameter-attribute" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="displayPattern"/>
 *                                 &lt;enumeration value="dbPattern"/>
 *                                 &lt;enumeration value="maxDate"/>
 *                                 &lt;enumeration value="minDate"/>
 *                                 &lt;enumeration value="dictionary"/>
 *                                 &lt;enumeration value="tree"/>
 *                                 &lt;enumeration value="treeUrl"/>
 *                                 &lt;enumeration value="treeHeight"/>
 *                                 &lt;enumeration value="observe"/>
 *                                 &lt;enumeration value="style"/>
 *                                 &lt;enumeration value="template"/>
 *                                 &lt;enumeration value="selectionMode"/>
 *                                 &lt;enumeration value="selectionTemplate"/>
 *                                 &lt;enumeration value="fieldName"/>
 *                                 &lt;enumeration value="fixparams"/>
 *                                 &lt;enumeration value="observetree"/>
 *                                 &lt;enumeration value="config"/>
 *                                 &lt;enumeration value="listeners"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{https://github.com/hongjinqiu/javameta/template}relationDS" minOccurs="0"/>
 *                   &lt;element name="defaultValueExpr" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="mode" default="text">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="text"/>
 *                                 &lt;enumeration value="js"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{https://github.com/hongjinqiu/javameta/template}query-param-attributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="formColumns" type="{http://www.w3.org/2001/XMLSchema}int" default="4" />
 *       &lt;attribute name="enableEnterParam" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dataSetId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fixedParameterOrQueryParameter"
})
@XmlRootElement(name = "query-parameters")
public class QueryParameters implements Serializable {
	private static final long serialVersionUID = 1L;

    @XmlElements({
        @XmlElement(name = "fixed-parameter", type = QueryParameters.FixedParameter.class),
        @XmlElement(name = "query-parameter", type = QueryParameters.QueryParameter.class)
    })
    protected List<Object> fixedParameterOrQueryParameter;
    @XmlAttribute
    protected Integer formColumns;
    @XmlAttribute
    protected Boolean enableEnterParam;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSetId;
    
    public List<QueryParameter> getQueryParameter() {
    	List<QueryParameter> list = New.arrayList();
    	
    	List<Object> parameters = getFixedParameterOrQueryParameter();
    	for (Object item: parameters) {
    		if (item instanceof QueryParameter) {
    			list.add((QueryParameter)item);
    		}
    	}
    	
    	return list;
    }

    /**
     * Gets the value of the fixedParameterOrQueryParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixedParameterOrQueryParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixedParameterOrQueryParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueryParameters.FixedParameter }
     * {@link QueryParameters.QueryParameter }
     * 
     * 
     */
    public List<Object> getFixedParameterOrQueryParameter() {
        if (fixedParameterOrQueryParameter == null) {
            fixedParameterOrQueryParameter = new ArrayList<Object>();
        }
        return this.fixedParameterOrQueryParameter;
    }

    /**
     * Gets the value of the formColumns property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFormColumns() {
        return formColumns;
    }

    /**
     * Sets the value of the formColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFormColumns(Integer value) {
        this.formColumns = value;
    }

    /**
     * Gets the value of the enableEnterParam property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableEnterParam() {
        return enableEnterParam;
    }

	public Boolean getEnableEnterParam() {
        return enableEnterParam;
    }

    /**
     * Sets the value of the enableEnterParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableEnterParam(Boolean value) {
        this.enableEnterParam = value;
    }

    /**
     * Gets the value of the dataSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetId() {
        return dataSetId;
    }

    /**
     * Sets the value of the dataSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetId(String value) {
        this.dataSetId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{https://github.com/hongjinqiu/javameta/template}query-param-attributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FixedParameter implements Serializable {
		private static final long serialVersionUID = 1L;

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String name;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String text;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String columnName;
        @XmlAttribute
        protected Boolean enterParam;
        @XmlAttribute
        protected Boolean auto;
        @XmlAttribute
        protected String editor;
        @XmlAttribute
        protected String restriction;
        @XmlAttribute
        protected Integer colSpan;
        @XmlAttribute
        protected Integer rowSpan;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String value;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String otherName;
        @XmlAttribute
        protected Boolean having;
        @XmlAttribute
        protected Boolean required;
        @XmlAttribute(name = "use-in")
        protected String useIn;
        @XmlAttribute
        protected Boolean readOnly;
        @XmlAttribute
        protected String dsFieldMap;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the columnName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColumnName() {
            return columnName;
        }

        /**
         * Sets the value of the columnName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColumnName(String value) {
            this.columnName = value;
        }

        /**
         * Gets the value of the enterParam property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isEnterParam() {
            return enterParam;
        }

	public Boolean getEnterParam() {
            return enterParam;
        }

        /**
         * Sets the value of the enterParam property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEnterParam(Boolean value) {
            this.enterParam = value;
        }

        /**
         * Gets the value of the auto property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAuto() {
            return auto;
        }

	public Boolean getAuto() {
            return auto;
        }

        /**
         * Sets the value of the auto property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAuto(Boolean value) {
            this.auto = value;
        }

        /**
         * Gets the value of the editor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEditor() {
            return editor;
        }

        /**
         * Sets the value of the editor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEditor(String value) {
            this.editor = value;
        }

        /**
         * Gets the value of the restriction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRestriction() {
            return restriction;
        }

        /**
         * Sets the value of the restriction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRestriction(String value) {
            this.restriction = value;
        }

        /**
         * Gets the value of the colSpan property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getColSpan() {
            return colSpan;
        }

        /**
         * Sets the value of the colSpan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setColSpan(Integer value) {
            this.colSpan = value;
        }

        /**
         * Gets the value of the rowSpan property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRowSpan() {
            return rowSpan;
        }

        /**
         * Sets the value of the rowSpan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRowSpan(Integer value) {
            this.rowSpan = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the otherName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOtherName() {
            return otherName;
        }

        /**
         * Sets the value of the otherName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOtherName(String value) {
            this.otherName = value;
        }

        /**
         * Gets the value of the having property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isHaving() {
            return having;
        }

	public Boolean getHaving() {
            return having;
        }

        /**
         * Sets the value of the having property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setHaving(Boolean value) {
            this.having = value;
        }

        /**
         * Gets the value of the required property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRequired() {
            return required;
        }

	public Boolean getRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRequired(Boolean value) {
            this.required = value;
        }

        /**
         * Gets the value of the useIn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUseIn() {
            return useIn;
        }

        /**
         * Sets the value of the useIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUseIn(String value) {
            this.useIn = value;
        }

        /**
         * Gets the value of the readOnly property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isReadOnly() {
            return readOnly;
        }

	public Boolean getReadOnly() {
            return readOnly;
        }

        /**
         * Sets the value of the readOnly property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setReadOnly(Boolean value) {
            this.readOnly = value;
        }

        /**
         * Gets the value of the dsFieldMap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDsFieldMap() {
            return dsFieldMap;
        }

        /**
         * Sets the value of the dsFieldMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDsFieldMap(String value) {
            this.dsFieldMap = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parameter-attribute" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="displayPattern"/>
     *                       &lt;enumeration value="dbPattern"/>
     *                       &lt;enumeration value="maxDate"/>
     *                       &lt;enumeration value="minDate"/>
     *                       &lt;enumeration value="dictionary"/>
     *                       &lt;enumeration value="tree"/>
     *                       &lt;enumeration value="treeUrl"/>
     *                       &lt;enumeration value="treeHeight"/>
     *                       &lt;enumeration value="observe"/>
     *                       &lt;enumeration value="style"/>
     *                       &lt;enumeration value="template"/>
     *                       &lt;enumeration value="selectionMode"/>
     *                       &lt;enumeration value="selectionTemplate"/>
     *                       &lt;enumeration value="fieldName"/>
     *                       &lt;enumeration value="fixparams"/>
     *                       &lt;enumeration value="observetree"/>
     *                       &lt;enumeration value="config"/>
     *                       &lt;enumeration value="listeners"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{https://github.com/hongjinqiu/javameta/template}relationDS" minOccurs="0"/>
     *         &lt;element name="defaultValueExpr" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="mode" default="text">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="text"/>
     *                       &lt;enumeration value="js"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{https://github.com/hongjinqiu/javameta/template}query-param-attributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameterAttribute",
        "relationDS",
        "defaultValueExpr"
    })
    public static class QueryParameter implements Serializable {
		private static final long serialVersionUID = 1L;

        @XmlElement(name = "parameter-attribute")
        protected List<QueryParameters.QueryParameter.ParameterAttribute> parameterAttribute;
        protected RelationDS relationDS;
        protected QueryParameters.QueryParameter.DefaultValueExpr defaultValueExpr;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String name;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String text;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String columnName;
        @XmlAttribute
        protected Boolean enterParam;
        @XmlAttribute
        protected Boolean auto;
        @XmlAttribute
        protected String editor;
        @XmlAttribute
        protected String restriction;
        @XmlAttribute
        protected Integer colSpan;
        @XmlAttribute
        protected Integer rowSpan;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String value;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String otherName;
        @XmlAttribute
        protected Boolean having;
        @XmlAttribute
        protected Boolean required;
        @XmlAttribute(name = "use-in")
        protected String useIn;
        @XmlAttribute
        protected Boolean readOnly;
        @XmlAttribute
        protected String dsFieldMap;
        
        public String getDbQueryName() {
        	if (StringUtils.isNotEmpty(columnName)) {
        		return columnName;
        	}
        	return name;
        }

        /**
         * Gets the value of the parameterAttribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameterAttribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameterAttribute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QueryParameters.QueryParameter.ParameterAttribute }
         * 
         * 
         */
        public List<QueryParameters.QueryParameter.ParameterAttribute> getParameterAttribute() {
            if (parameterAttribute == null) {
                parameterAttribute = new ArrayList<QueryParameters.QueryParameter.ParameterAttribute>();
            }
            return this.parameterAttribute;
        }

        /**
         * Gets the value of the relationDS property.
         * 
         * @return
         *     possible object is
         *     {@link RelationDS }
         *     
         */
        public RelationDS getRelationDS() {
            return relationDS;
        }

        /**
         * Sets the value of the relationDS property.
         * 
         * @param value
         *     allowed object is
         *     {@link RelationDS }
         *     
         */
        public void setRelationDS(RelationDS value) {
            this.relationDS = value;
        }

        /**
         * Gets the value of the defaultValueExpr property.
         * 
         * @return
         *     possible object is
         *     {@link QueryParameters.QueryParameter.DefaultValueExpr }
         *     
         */
        public QueryParameters.QueryParameter.DefaultValueExpr getDefaultValueExpr() {
            return defaultValueExpr;
        }

        /**
         * Sets the value of the defaultValueExpr property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryParameters.QueryParameter.DefaultValueExpr }
         *     
         */
        public void setDefaultValueExpr(QueryParameters.QueryParameter.DefaultValueExpr value) {
            this.defaultValueExpr = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the columnName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColumnName() {
            return columnName;
        }

        /**
         * Sets the value of the columnName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColumnName(String value) {
            this.columnName = value;
        }

        /**
         * Gets the value of the enterParam property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isEnterParam() {
            return enterParam;
        }

	public Boolean getEnterParam() {
            return enterParam;
        }

        /**
         * Sets the value of the enterParam property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEnterParam(Boolean value) {
            this.enterParam = value;
        }

        /**
         * Gets the value of the auto property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAuto() {
            return auto;
        }

	public Boolean getAuto() {
            return auto;
        }

        /**
         * Sets the value of the auto property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAuto(Boolean value) {
            this.auto = value;
        }

        /**
         * Gets the value of the editor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEditor() {
            return editor;
        }

        /**
         * Sets the value of the editor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEditor(String value) {
            this.editor = value;
        }

        /**
         * Gets the value of the restriction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRestriction() {
            return restriction;
        }

        /**
         * Sets the value of the restriction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRestriction(String value) {
            this.restriction = value;
        }

        /**
         * Gets the value of the colSpan property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getColSpan() {
            return colSpan;
        }

        /**
         * Sets the value of the colSpan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setColSpan(Integer value) {
            this.colSpan = value;
        }

        /**
         * Gets the value of the rowSpan property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRowSpan() {
            return rowSpan;
        }

        /**
         * Sets the value of the rowSpan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRowSpan(Integer value) {
            this.rowSpan = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the otherName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOtherName() {
            return otherName;
        }

        /**
         * Sets the value of the otherName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOtherName(String value) {
            this.otherName = value;
        }

        /**
         * Gets the value of the having property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isHaving() {
            return having;
        }

	public Boolean getHaving() {
            return having;
        }

        /**
         * Sets the value of the having property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setHaving(Boolean value) {
            this.having = value;
        }

        /**
         * Gets the value of the required property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRequired() {
            return required;
        }

	public Boolean getRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRequired(Boolean value) {
            this.required = value;
        }

        /**
         * Gets the value of the useIn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUseIn() {
            return useIn;
        }

        /**
         * Sets the value of the useIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUseIn(String value) {
            this.useIn = value;
        }

        /**
         * Gets the value of the readOnly property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isReadOnly() {
            return readOnly;
        }

	public Boolean getReadOnly() {
            return readOnly;
        }

        /**
         * Sets the value of the readOnly property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setReadOnly(Boolean value) {
            this.readOnly = value;
        }

        /**
         * Gets the value of the dsFieldMap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDsFieldMap() {
            return dsFieldMap;
        }

        /**
         * Sets the value of the dsFieldMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDsFieldMap(String value) {
            this.dsFieldMap = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="mode" default="text">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="text"/>
         *             &lt;enumeration value="js"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DefaultValueExpr implements Serializable {
		private static final long serialVersionUID = 1L;

            @XmlValue
            protected String value;
            @XmlAttribute
            protected String mode;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the mode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMode() {
                return mode;
            }

            /**
             * Sets the value of the mode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMode(String value) {
                this.mode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="displayPattern"/>
         *             &lt;enumeration value="dbPattern"/>
         *             &lt;enumeration value="maxDate"/>
         *             &lt;enumeration value="minDate"/>
         *             &lt;enumeration value="dictionary"/>
         *             &lt;enumeration value="tree"/>
         *             &lt;enumeration value="treeUrl"/>
         *             &lt;enumeration value="treeHeight"/>
         *             &lt;enumeration value="observe"/>
         *             &lt;enumeration value="style"/>
         *             &lt;enumeration value="template"/>
         *             &lt;enumeration value="selectionMode"/>
         *             &lt;enumeration value="selectionTemplate"/>
         *             &lt;enumeration value="fieldName"/>
         *             &lt;enumeration value="fixparams"/>
         *             &lt;enumeration value="observetree"/>
         *             &lt;enumeration value="config"/>
         *             &lt;enumeration value="listeners"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ParameterAttribute implements Serializable {
		private static final long serialVersionUID = 1L;

            @XmlAttribute(required = true)
            protected String name;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
